### ISSUE TITLE
Utiliser Docker

### ISSUE THREAD

**Issue by Wonderfall** [dieulot/jvforum#8]
Je propose l'utilisation de Docker pour le déploiement de jvforum. Je ne sais pas si tu es familier avec Docker, sinon il faut me le dire. C'est assez simple, je propose le Dockerfile suivant (testé, et fonctionnel) : 

```
FROM xataz/node:6.2

ENV UID=991 \
    GID=991 \
    COOKIES_SECRET=secret \
    DB_HOST=localhost \
    DB_USER=root \
    DB_PASSWORD=password \
    DATABASE=jvforum \
    GOOGLE_ANALYTICS_ID=ga_id

WORKDIR /jvforum

RUN echo "@commuedge https://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
 && apk -U add git su-exec tini@commuedge \
 && git clone https://github.com/dieulot/jvforum.git . \
 && npm install \
 && cp config/example.js config/development.js \
 && apk del git \
 && rm -f /var/cache/apk/*

COPY run.sh /usr/local/bin/run.sh

RUN chmod +x /usr/local/bin/run.sh

EXPOSE 3000

CMD ["/sbin/tini","--","run.sh"]
```

```
#!/bin/sh
sed -i -e "s/cookiesSecret: 'secret'/cookiesSecret: '$COOKIES_SECRET'/g" \
       -e "s/host: 'localhost'/host: '$DB_HOST'/g" \
       -e "s/user: 'root'/user: '$DB_USER'/g" \
       -e "s/password: ''/password: '$DB_PASSWORD'/g" \
       -e "s/database: 'jvforum'/database: '$DATABASE'/g" \
       -e "s/googleAnalyticsId: ''/googleAnalyticsId: '$GOOGLE_ANALYTICS_ID'/g" \
       config/development.js

chown -R $UID:$GID .
su-exec $UID:$GID npm start
```

L'image de base est elle-même basée sur Alpine Linux, ce qui fait sa légèreté. Maintenant pour lancer toute l'application avec nginx et MySQL, je propose un docker-compose, qui est le suivant : 

```
nginx:
  image: wonderfall/nginx
  container_name: nginx
  links:
    - jvforum:jvforum
  ports:
    - "80:8000"
    - "443:4430"
  volumes:
    - ./nginx/sites:/sites-enabled
    - ./nginx/conf:/conf.d
    - ./nginx/log:/var/log/nginx

jvforum:
  image: jvforum/jvforum
  container_name: jvforum
  links:
    - db_jvforum:db_jvforum
  environment:
    - UID=991
    - GID=991
    - COOKIES_SECRET=secret
    - DB_HOST=db_jvforum
    - DB_USER=jvforum
    - DB_PASSWORD=onche
    - DATABASE=jvforum
    - GOOGLE_ANALYTICS_ID=ga_id

db_jvforum:
  image: mariadb:10
  container_name: db_jvforum
  volumes:
    - ./jvforum/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=supersecretpassword
    - MYSQL_DATABASE=jvforum
    - MYSQL_USER=jvforum
    - MYSQL_PASSWORD=onche
```

Il faudra bien évidemment modifier les variables d'environnement et ajouter un vhost dans `./nginx/sites`, ce qui peut être automatisé en lançant `ngxproxy` depuis le conteneur nginx. Je peux faire le vhost, sinon. Faudra juste faire un `proxy_pass http://jvforum:3000` quoi.

Concernant `schema.sql`, un `docker exec -ti db_jvforum mysql -u jvforum -p jvforum < schema.sql` fera l'affaire.

Pour build l'image `jvforum`, je propose, si l'idée est retenue, d'ajouter ces fichiers au projet, comme ça on peut utiliser Docker Hub et créer un repo qui sera lié à ce Github. Ainsi à chaque commit, le Hub va construire une nouvelle image. On peut faire plusieurs tags, disons un tag `stable`qui correspond à la production et un tag `dev` pour le développement, chaque tag peut être attribué à une branche du projet. Bref, je peux détailler davantage si nécessaire, le tout est plus facile à prendre en main qu'on ne le pense.

Alors qu'en penses-tu ? Je peux aider de A à Z dans la mise en place, et/ou répondre à d'éventuelles questions.
